KooliProjekt/Models/ErrorViewModel.cs
namespace KooliProjekt.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KooliProjekt/Models/TodoListsIndexModel.cs
using KooliProjekt.Data;
using KooliProjekt.Search;

namespace KooliProjekt.Models
{
    public class TodoListsIndexModel
    {
        public TodoListsSearch Search { get; set; }
        public PagedResult<TodoList> Data { get; set; }
    }
}

KooliProjekt/Components/PagerViewComponent.cs
using KooliProjekt.Data;
using Microsoft.AspNetCore.Mvc;

namespace KooliProjekt.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

KooliProjekt/Controllers/HomeController.cs
using KooliProjekt.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KooliProjekt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KooliProjekt/Controllers/TodoListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KooliProjekt.Data;
using KooliProjekt.Services;
using KooliProjekt.Search;
using KooliProjekt.Models;

namespace KooliProjekt.Controllers
{
    public class TodoListsController : Controller
    {
        private readonly ITodoListService _todoListService;

        public TodoListsController(ITodoListService todoListService)
        {
            _todoListService = todoListService;
        }

        // GET: TodoLists
        public async Task<IActionResult> Index(int page = 1, TodoListsIndexModel model = null)
        {
            model = model ?? new TodoListsIndexModel();
            model.Data = await _todoListService.List(page, 5, model.Search);

            return View(model);
        }

        // GET: TodoLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoList = await _todoListService.Get(id.Value);
            if (todoList == null)
            {
                return NotFound();
            }

            return View(todoList);
        }

        // GET: TodoLists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TodoLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title")] TodoList todoList)
        {
            if (ModelState.IsValid)
            {
                await _todoListService.Save(todoList);

                return RedirectToAction(nameof(Index));
            }
            return View(todoList);
        }

        // GET: TodoLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoList = await _todoListService.Get(id.Value);
            if (todoList == null)
            {
                return NotFound();
            }
            return View(todoList);
        }

        // POST: TodoLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] TodoList todoList)
        {
            if (id != todoList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _todoListService.Save(todoList);
                return RedirectToAction(nameof(Index));
            }
            return View(todoList);
        }

        // GET: TodoLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoList = await _todoListService.Get(id.Value);
            if (todoList == null)
            {
                return NotFound();
            }

            return View(todoList);
        }

        // POST: TodoLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _todoListService.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

KooliProjekt/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

KooliProjekt/Views/Shared/Components/Pager/Default.cshtml
@model PagedResultBase
@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);
}

<div class="row">
    @* <div class="col-md-4 col-sm-4 items-info">
        Items @Model.FirstRowOnPage to @Model.LastRowOnPage of @Model.RowCount total
    </div> *@
    <div class="col-md-8 col-sm-8">
        @if (Model.PageCount > 1)
        {
            <ul class="pagination pull-right">
                <li><a href="@urlTemplate.Replace("{0}", "1")">&laquo;</a></li>
                @for (var i = startIndex; i <= finishIndex; i++)
                {
                    @if (i == Model.CurrentPage)
                    {
                        <li><span>@i</span></li>
                    }
                    else
                    {
                        <li><a href="@urlTemplate.Replace("{0}", i.ToString())">@i</a></li>
                    }
                }
                <li><a href="@urlTemplate.Replace("{0}", Model.PageCount.ToString())">&raquo;</a></li>
            </ul>
        }
    </div>
</div>

KooliProjekt/Views/Shared/_Comments.cshtml

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

KooliProjekt/Views/Shared/_Footer.cshtml
<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-4 col-sm-4 padding-top-10">
                2022 © Tublid õpilased. ALL Rights Reserved.
            </div>
            <!-- END COPYRIGHT -->
            <!-- BEGIN PAYMENTS -->
            <div class="col-md-4 col-sm-4">
                <ul class="list-unstyled list-inline pull-right">
                    <li><img src="~/assets/corporate/img/payments/western-union.jpg" alt="We accept Western Union" title="We accept Western Union"></li>
                    <li><img src="~/assets/corporate/img/payments/american-express.jpg" alt="We accept American Express" title="We accept American Express"></li>
                    <li><img src="~/assets/corporate/img/payments/MasterCard.jpg" alt="We accept MasterCard" title="We accept MasterCard"></li>
                    <li><img src="~/assets/corporate/img/payments/PayPal.jpg" alt="We accept PayPal" title="We accept PayPal"></li>
                    <li><img src="~/assets/corporate/img/payments/visa.jpg" alt="We accept Visa" title="We accept Visa"></li>
                </ul>
            </div>
            <!-- END PAYMENTS -->
            <!-- BEGIN POWERED -->
            <div class="col-md-4 col-sm-4 text-right">
                <p class="powered">Powered by: Metronic & ASP.NET Core</p>
            </div>
            <!-- END POWERED -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

KooliProjekt/Views/Shared/_Header.cshtml
<!-- BEGIN HEADER -->
<div class="header">
    <div class="container">
        <a class="site-logo" asp-controller="Home"><img src="~/assets/corporate/img/logos/logo-red.png" alt="Metronic Shop UI"></a>

        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

        @*<partial name="_TopShoppingCard" />*@

        <!-- BEGIN NAVIGATION -->
        <div class="header-navigation">
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>

                <!-- BEGIN TOP SEARCH -->
                <li class="menu-search">
                    <span class="sep"></span>
                    <i class="fa fa-search search-btn"></i>
                    <div class="search-box">
                        <form action="#">
                            <div class="input-group">
                                <input type="text" placeholder="Search" class="form-control">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="submit">Search</button>
                                </span>
                            </div>
                        </form>
                    </div>
                </li>
                <!-- END TOP SEARCH -->
            </ul>
        </div>
        <!-- END NAVIGATION -->
    </div>
</div>
<!-- Header END -->

KooliProjekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title>Kooliprojekt</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <meta property="og:site_name" content="-CUSTOMER VALUE-">
    <meta property="og:title" content="-CUSTOMER VALUE-">
    <meta property="og:description" content="-CUSTOMER VALUE-">
    <meta property="og:type" content="website">
    <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
    <meta property="og:url" content="-CUSTOMER VALUE-">

    <link rel="shortcut icon" href="favicon.ico">

    <!-- Fonts START -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css"><!--- fonts for slider on the index page -->
    <!-- Fonts END -->
    <!-- Global styles START -->
    <link href="~/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->
    <!-- Page level plugin styles START -->
    <link href="~/assets/pages/css/animate.css" rel="stylesheet">
    <link href="~/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="~/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <!-- Page level plugin styles END -->
    <!-- Theme styles START -->
    <link href="~/assets/pages/css/components.css" rel="stylesheet">
    <link href="~/assets/pages/css/slider.css" rel="stylesheet">
    <link href="~/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="~/assets/corporate/css/style.css" rel="stylesheet">
    <link href="~/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="~/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="~/assets/corporate/css/custom.css" rel="stylesheet">
    <!-- Theme styles END -->
</head>
<body class="ecommerce">
    @*<partial name="_TopBar" />*@
    <partial name="_Header" />
    <div class="main">
        <div class="container">
            @*<ul class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li><a href="">Store</a></li>
                <li class="active">Cool green dress with red bell</li>
            </ul>*@
            <div class="row margin-bottom-40">
                <partial name="_SideBar" />

                <!-- BEGIN CONTENT -->
                <div class="col-md-9 col-sm-7">
                    @RenderBody()
                </div>
                <!-- END CONTENT -->
            </div>
        </div>
    </div>

    <partial name="_Footer" />

    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS (REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="~/assets/plugins/respond.min.js"></script>
    <![endif]-->
    <script src="~/assets/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="~/assets/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/corporate/scripts/back-to-top.js" type="text/javascript"></script>
    <script src="~/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="~/assets/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="~/assets/plugins/owl.carousel/owl.carousel.min.js" type="text/javascript"></script><!-- slider for products -->
    <script src='~/assets/plugins/zoom/jquery.zoom.min.js' type="text/javascript"></script><!-- product zoom -->
    <script src="~/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script><!-- Quantity -->

    <script src="~/assets/corporate/scripts/layout.js" type="text/javascript"></script>
    <script src="~/assets/pages/scripts/bs-carousel.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            Layout.init();
            Layout.initOWL();
            Layout.initImageZoom();
            Layout.initTouchspin();
            Layout.initTwitter();
        });
    </script>
    <!-- END PAGE LEVEL JAVASCRIPTS -->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

KooliProjekt/Views/Shared/_SideBar.cshtml
<!-- BEGIN SIDEBAR -->
<div class="sidebar col-md-3 col-sm-5">
    <ul class="list-group margin-bottom-25 sidebar-menu">
        <li class="list-group-item clearfix"><a href="../"><i class="fa fa-angle-right"></i> Home</a></li>
        @*<li class="list-group-item clearfix dropdown active">
        <a href="../" class="collapsed">
            <i class="fa fa-angle-right"></i>
            Home

        </a>
        <ul class="dropdown-menu" style="display:block;">
            <li class="list-group-item dropdown clearfix active">
                <a href="shop-product-list.html" class="collapsed"><i class="fa fa-angle-right"></i> Shoes </a>
                <ul class="dropdown-menu" style="display:block;">
                    <li class="list-group-item dropdown clearfix">
                        <a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Classic </a>
                        <ul class="dropdown-menu">
                            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Classic 1</a></li>
                            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Classic 2</a></li>
                        </ul>
                    </li>
                    <li class="list-group-item dropdown clearfix active">
                        <a href="shop-product-list.html" class="collapsed"><i class="fa fa-angle-right"></i> Sport  </a>
                        <ul class="dropdown-menu" style="display:block;">
                            <li class="active"><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Sport 1</a></li>
                            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Sport 2</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Trainers</a></li>
            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Jeans</a></li>
            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> Chinos</a></li>
            <li><a href="shop-product-list.html"><i class="fa fa-angle-right"></i> T-Shirts</a></li>
        </ul>
        </li>*@
    </ul>
</div>
<!-- END SIDEBAR -->

KooliProjekt/Views/Shared/_Tabs.cshtml
<div class="product-page-content">
    <ul id="myTab" class="nav nav-tabs">
        <li><a href="#Description" data-toggle="tab">Description</a></li>
        <li><a href="#Information" data-toggle="tab">Information</a></li>
        <li class="active"><a href="#Reviews" data-toggle="tab">Reviews (2)</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade" id="Description">
            <partial name="_Tabs_Description" />
        </div>
        <div class="tab-pane fade" id="Information">
            <partial name="_Tabs_Information" />
        </div>
        <div class="tab-pane fade in active" id="Reviews">
            <partial name="_Tabs_Reviews" />
        </div>
    </div>
</div>

KooliProjekt/Views/Shared/_Tabs_Description.cshtml
<p>Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed sit nonumy nibh sed euismod laoreet dolore magna aliquarm erat sit volutpat Nostrud duis molestie at dolore. Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed sit nonumy nibh sed euismod laoreet dolore magna aliquarm erat sit volutpat Nostrud duis molestie at dolore. Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed sit nonumy nibh sed euismod laoreet dolore magna aliquarm erat sit volutpat Nostrud duis molestie at dolore. </p>

KooliProjekt/Views/Shared/_Tabs_Information.cshtml
<table class="datasheet">
    <tr>
        <th colspan="2">Additional features</th>
    </tr>
    <tr>
        <td class="datasheet-features-type">Value 1</td>
        <td>21 cm</td>
    </tr>
    <tr>
        <td class="datasheet-features-type">Value 2</td>
        <td>700 gr.</td>
    </tr>
    <tr>
        <td class="datasheet-features-type">Value 3</td>
        <td>10 person</td>
    </tr>
    <tr>
        <td class="datasheet-features-type">Value 4</td>
        <td>14 cm</td>
    </tr>
    <tr>
        <td class="datasheet-features-type">Value 5</td>
        <td>plastic</td>
    </tr>
</table>

KooliProjekt/Views/Shared/_Tabs_Reviews.cshtml
<!--<p>There are no reviews for this product.</p>-->
<div class="review-item clearfix">
    <div class="review-item-submitted">
        <strong>Bob</strong>
        <em>30/12/2013 - 07:37</em>
        <div class="rateit" data-rateit-value="5" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
    </div>
    <div class="review-item-content">
        <p>Sed velit quam, auctor id semper a, hendrerit eget justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel arcu pulvinar dolor tempus feugiat id in orci. Phasellus sed erat leo. Donec luctus, justo eget ultricies tristique, enim mauris bibendum orci, a sodales lectus purus ut lorem.</p>
    </div>
</div>
<div class="review-item clearfix">
    <div class="review-item-submitted">
        <strong>Mary</strong>
        <em>13/12/2013 - 17:49</em>
        <div class="rateit" data-rateit-value="2.5" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
    </div>
    <div class="review-item-content">
        <p>Sed velit quam, auctor id semper a, hendrerit eget justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel arcu pulvinar dolor tempus feugiat id in orci. Phasellus sed erat leo. Donec luctus, justo eget ultricies tristique, enim mauris bibendum orci, a sodales lectus purus ut lorem.</p>
    </div>
</div>

<!-- BEGIN FORM-->
<form action="#" class="reviews-form" role="form">
    <h2>Write a review</h2>
    <div class="form-group">
        <label for="name">Name <span class="require">*</span></label>
        <input type="text" class="form-control" id="name">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" id="email">
    </div>
    <div class="form-group">
        <label for="review">Review <span class="require">*</span></label>
        <textarea class="form-control" rows="8" id="review"></textarea>
    </div>
    <div class="form-group">
        <label for="email">Rating</label>
        <input type="range" value="4" step="0.25" id="backing5">
        <div class="rateit" data-rateit-backingfld="#backing5" data-rateit-resetable="false" data-rateit-ispreset="true" data-rateit-min="0" data-rateit-max="5">
        </div>
    </div>
    <div class="padding-top-20">
        <button type="submit" class="btn btn-primary">Send</button>
    </div>
</form>
<!-- END FORM-->

KooliProjekt/Views/Shared/_TopBar.cshtml
<!-- BEGIN TOP BAR -->
<div class="pre-header">
    <div class="container">
        <div class="row">
            <!-- BEGIN TOP BAR LEFT PART -->
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span>+1 456 6717</span></li>
                    <!-- BEGIN CURRENCIES -->
                    <li class="shop-currencies">
                        <a href="javascript:void(0);">€</a>
                        <a href="javascript:void(0);">£</a>
                        <a href="javascript:void(0);" class="current">$</a>
                    </li>
                    <!-- END CURRENCIES -->
                    <!-- BEGIN LANGS -->
                    <li class="langs-block">
                        <a href="javascript:void(0);" class="current">English </a>
                        <div class="langs-block-others-wrapper">
                            <div class="langs-block-others">
                                <a href="javascript:void(0);">French</a>
                                <a href="javascript:void(0);">Germany</a>
                                <a href="javascript:void(0);">Turkish</a>
                            </div>
                        </div>
                    </li>
                    <!-- END LANGS -->
                </ul>
            </div>
            <!-- END TOP BAR LEFT PART -->
            <!-- BEGIN TOP BAR MENU -->
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    <li><a href="shop-account.html">My Account</a></li>
                    <li><a href="shop-wishlist.html">My Wishlist</a></li>
                    <li><a href="shop-checkout.html">Checkout</a></li>
                    @*<partial name="_LoginPartial" />*@
                </ul>
            </div>
            <!-- END TOP BAR MENU -->
        </div>
    </div>
</div>
<!-- END TOP BAR -->

KooliProjekt/Views/TodoLists/Create.cshtml
@model KooliProjekt.Data.TodoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TodoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KooliProjekt/Views/TodoLists/Delete.cshtml
@model KooliProjekt.Data.TodoList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KooliProjekt/Views/TodoLists/Details.cshtml
@model KooliProjekt.Data.TodoList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TodoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

KooliProjekt/Views/TodoLists/Index.cshtml
@model TodoListsIndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form method="get">
    <div class="form-group">
        <label class="control-label">Märksõna</label>
        <input asp-for="Search.Keyword" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">Kõik itemid tehtud</label>
        <select asp-for="Search.Done" class="form-control">
            <option value="">-</option>
            <option value="true">Jah</option>
            <option value="false">Ei</option>
        </select>        
    </div>
    <div class="form-group">
        <button class="btn btn-primary">Otsi</button>
        <a asp-controller="TodoLists" asp-action="Index" class="btn btn-primary">Reset</a>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Data.Results[0].Title)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Data) 
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

@(await Component.InvokeAsync<PagerViewComponent>(Model.Data))